name: 'ga4_metrics'
version: '1.0.0'

config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]


vars:
  ga4_events_src: "{{ source('ga4', 'events') }}" 


models:
  ga4_metrics:
    sessions:
      +materialized: table
      tmp:
        +materialized: view
    traffic_metrics:
      +materialized: table
