name: 'ga4_metrics'
version: '1.0.0'

config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

# TODO: remove before open sourcing
profile: 'ga4_metrics'


vars:
  ga4_events_src: "{{ source('ga4', 'events') }}" 

  # TODO: remove before open sourcing
  ga4_schema: "analytics_338563309"


models:
  ga4_metrics:
    sessions:
      +materialized: table
      tmp:
        +materialized: view
    traffic_metrics:
      +materialized: table
    